// Generated by mykg emit_load_csv. Do not edit by hand.

// 1. Constraint
CREATE CONSTRAINT _mykgnode_id_unique IF NOT EXISTS
FOR (n:_MykgNode) REQUIRE n.id IS UNIQUE;

// 2. Nodes — one block per label

:auto LOAD CSV WITH HEADERS FROM 'file:/nodes_Organization.csv' AS row
CALL {
  WITH row
  MERGE (n:_MykgNode {id: row.id})
  SET n:Organization
  SET
      n._node_confidence = CASE WHEN row._node_confidence = '' THEN null ELSE toFloat(row._node_confidence) END,
      n._parents = CASE WHEN row._parents = '' THEN [] ELSE split(row._parents, ';') END,
      n._source_files = CASE WHEN row._source_files = '' THEN [] ELSE split(row._source_files, ';') END,
      n.industry = CASE WHEN row.industry = '' THEN null ELSE row.industry END,
      n.industry_confidence = CASE WHEN row.industry_confidence = '' THEN null ELSE toFloat(row.industry_confidence) END,
      n.name = CASE WHEN row.name = '' THEN null ELSE row.name END,
      n.name_confidence = CASE WHEN row.name_confidence = '' THEN null ELSE toFloat(row.name_confidence) END
} IN TRANSACTIONS OF 1000 ROWS;

:auto LOAD CSV WITH HEADERS FROM 'file:/nodes_Person.csv' AS row
CALL {
  WITH row
  MERGE (n:_MykgNode {id: row.id})
  SET n:Person
  SET
      n._aliases = CASE WHEN row._aliases = '' THEN [] ELSE split(row._aliases, ';') END,
      n._node_confidence = CASE WHEN row._node_confidence = '' THEN null ELSE toFloat(row._node_confidence) END,
      n._parents = CASE WHEN row._parents = '' THEN [] ELSE split(row._parents, ';') END,
      n._source_files = CASE WHEN row._source_files = '' THEN [] ELSE split(row._source_files, ';') END,
      n.email = CASE WHEN row.email = '' THEN null ELSE row.email END,
      n.email_confidence = CASE WHEN row.email_confidence = '' THEN null ELSE toFloat(row.email_confidence) END,
      n.name = CASE WHEN row.name = '' THEN null ELSE row.name END,
      n.name_confidence = CASE WHEN row.name_confidence = '' THEN null ELSE toFloat(row.name_confidence) END
} IN TRANSACTIONS OF 1000 ROWS;

:auto LOAD CSV WITH HEADERS FROM 'file:/nodes_SoftwareEngineer.csv' AS row
CALL {
  WITH row
  MERGE (n:_MykgNode {id: row.id})
  SET n:SoftwareEngineer
  SET
      n._aliases = CASE WHEN row._aliases = '' THEN [] ELSE split(row._aliases, ';') END,
      n._node_confidence = CASE WHEN row._node_confidence = '' THEN null ELSE toFloat(row._node_confidence) END,
      n._parents = CASE WHEN row._parents = '' THEN [] ELSE split(row._parents, ';') END,
      n._source_files = CASE WHEN row._source_files = '' THEN [] ELSE split(row._source_files, ';') END,
      n.email = CASE WHEN row.email = '' THEN null ELSE row.email END,
      n.email_confidence = CASE WHEN row.email_confidence = '' THEN null ELSE toFloat(row.email_confidence) END,
      n.name = CASE WHEN row.name = '' THEN null ELSE row.name END,
      n.name_confidence = CASE WHEN row.name_confidence = '' THEN null ELSE toFloat(row.name_confidence) END,
      n.primary_language = CASE WHEN row.primary_language = '' THEN null ELSE row.primary_language END,
      n.primary_language_confidence = CASE WHEN row.primary_language_confidence = '' THEN null ELSE toFloat(row.primary_language_confidence) END
} IN TRANSACTIONS OF 1000 ROWS;

// 3. Edges — one block per rel-type

:auto LOAD CSV WITH HEADERS FROM 'file:/relationships_KNOWS.csv' AS row
CALL {
  WITH row
  MATCH (a:_MykgNode {id: row.from})
  MATCH (b:_MykgNode {id: row.to})
  MERGE (a)-[r:KNOWS]->(b)
  SET
      r.confidence = CASE WHEN row.confidence = '' THEN null ELSE toFloat(row.confidence) END,
      r.method = CASE WHEN row.method = '' THEN null ELSE row.method END,
      r.source_files = CASE WHEN row.source_files = '' THEN [] ELSE split(row.source_files, ';') END
} IN TRANSACTIONS OF 1000 ROWS;

:auto LOAD CSV WITH HEADERS FROM 'file:/relationships_LOCATED_IN.csv' AS row
CALL {
  WITH row
  MATCH (a:_MykgNode {id: row.from})
  MATCH (b:_MykgNode {id: row.to})
  MERGE (a)-[r:LOCATED_IN]->(b)
  SET
      r.confidence = CASE WHEN row.confidence = '' THEN null ELSE toFloat(row.confidence) END,
      r.method = CASE WHEN row.method = '' THEN null ELSE row.method END,
      r.source_files = CASE WHEN row.source_files = '' THEN [] ELSE split(row.source_files, ';') END
} IN TRANSACTIONS OF 1000 ROWS;

:auto LOAD CSV WITH HEADERS FROM 'file:/relationships_WORKS_AT.csv' AS row
CALL {
  WITH row
  MATCH (a:_MykgNode {id: row.from})
  MATCH (b:_MykgNode {id: row.to})
  MERGE (a)-[r:WORKS_AT]->(b)
  SET
      r.confidence = CASE WHEN row.confidence = '' THEN null ELSE toFloat(row.confidence) END,
      r.method = CASE WHEN row.method = '' THEN null ELSE row.method END,
      r.role = CASE WHEN row.role = '' THEN null ELSE row.role END,
      r.role_confidence = CASE WHEN row.role_confidence = '' THEN null ELSE toFloat(row.role_confidence) END,
      r.source_files = CASE WHEN row.source_files = '' THEN [] ELSE split(row.source_files, ';') END,
      r.start_date = CASE WHEN row.start_date = '' THEN null ELSE row.start_date END,
      r.start_date_confidence = CASE WHEN row.start_date_confidence = '' THEN null ELSE toFloat(row.start_date_confidence) END
} IN TRANSACTIONS OF 1000 ROWS;
